### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by ajai-akkarapaka** [profzei/NUC7i3BNH#1]
can u please post updates to the efi folder as I have used your folder and its working smooth except for usb-c hub. I am using this on my nuc 7 for my son's online classes.

**Comment by ajai-akkarapaka** [comment]
Hello Profzei., can you please share the updated EFI folder, Waiting to update the nuc since the April.

**Comment by profzei** [comment]
@ajai-akkarapaka 
I totally forgot to release updates... I'll do it during next week for sure!

**Comment by ajai-akkarapaka** [comment]
Thank you so much.. appreciate your effort

**Comment by ajai-akkarapaka** [comment]
Thanks for the updates

**Comment by ajai-akkarapaka** [comment]
there is some issues with the config.plist, unable to open it on Opencore configurator nor ProperTree. Guess some corruption during upload 👍

**Comment by profzei** [comment]
@ajai-akkarapaka 
Ahahah! You are right: the corruption in `config.plist` is only a space character on line 1 & column 1... just delete it!
I don't use `ProperTree` nor `OpenCore configuration`, but only `Sublime Text` or `CotEditor` which are general editors (not only for `xml` files)

**Comment by ajai-akkarapaka** [comment]
can you republish it. as I am not familiar with Sublime Text or CotEditor. Thanks

**Comment by ajai-akkarapaka** [comment]
done.. did that. now able to edit on proper tree.. 👍
