### ISSUE TITLE
After update, getting OC schema issues

### ISSUE THREAD

**Issue by ajai-akkarapaka** [profzei/NUC7i3BNH#2]
Hi, firstly thanks for your updates. the issue is, I am getting new schema issue when the NUC boots from the opencore EFI. Please find the attached pictures. 
![IMG_7759](https://user-images.githubusercontent.com/85277762/124821026-d3b16a80-df8b-11eb-9f35-347c3033e16a.jpg)
![IMG_7758](https://user-images.githubusercontent.com/85277762/124821035-d8761e80-df8b-11eb-87b5-d4d3d85977d9.jpg)

**Comment by ajai-akkarapaka** [comment]
[EFI.zip](https://github.com/profzei/NUC7i3BNH/files/6796922/EFI.zip)
Just updated to OC7.1 with latest kexts. The system is booting normal and everything seems good. Please have a look at the EFI folder and do let me know if we need to change any thing. Regards

**Comment by sash11** [comment]
I have booted with debug version of OC and found out that ProvideCustomSlide quirk is not needed:

OCABC: All slides are usable! You can disable ProvideCustomSlide!

**Comment by ajai-akkarapaka** [comment]
> I have booted with debug version of OC and found out that ProvideCustomSlide quirk is not needed:
> 
> OCABC: All slides are usable! You can disable ProvideCustomSlide!

Thanks.. will do and check again..

**Comment by ajai-akkarapaka** [comment]
Unable to verify it. It's critical for me to keep this system running. My son's using it for his school.
