### ISSUE TITLE
[HELP] macOS in Italian

### ISSUE THREAD

**Issue by topiga** [profzei/NUC7i3BNH#4]
Hi ! First, thanks a lot for your efforts on this model. I have an issue with the language of macOS, the installation is in Italian and I would like it to change. I changed the prev-lang:kbd, but ut doesn’t do anything. Do you have any ideas ?

**Comment by sash11** [comment]
Change prev-lang:kbd to String type and put en-US:0 for English for example.

**Comment by topiga** [comment]
It doesn’t change anything

**Comment by sash11** [comment]
Where do you get a different language? During the initial installation? Can you post a screen shot?

**Comment by topiga** [comment]
I get a different language in the installation phase, and the setup. I managed to install Big Sur in Italian, I changed the language after the setup.
